apiVersion: apps/v1
kind: Deployment
metadata:
  name: donation-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: donation-app
  template:
    metadata:
      labels:
        app: donation-app
    spec:
      containers:
        - name: donation-app
          image: yourdockerhubusername/online-donation-system:latest
          imagePullPolicy: Always
