apiVersion: v1
kind: Service
metadata:
  name: donation-service
spec:
  selector:
    app: donation-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30082
  type: NodePort
